# Convert and Copy Array

In [1]:
import numpy as np

In [2]:
liste = [1, 2, 3, 4]

In [3]:
array = np.array(liste)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
liste2 = list(array)

In [6]:
liste2

[1, 2, 3, 4]

In [7]:
type(liste2)

list

In [8]:
a = np.array([1, 2, 3, 4])

In [9]:
b = a
c = a

In [11]:
b[0]=5

In [12]:
a

array([5, 2, 3, 4])

görüldüğü gibi diziler birbirine eşitleniğinde herhangi birinde yapılan değişiklik hepsini etkiliyor. Bunun önüne geçmek için copy fonksiyonu kullanılır.

In [13]:
d = np.array([9, 8, 7, 6])

In [14]:
e = d.copy()
f = d.copy()

In [15]:
e[2]=3

In [18]:
e

array([9, 8, 3, 6])

In [19]:
d

array([9, 8, 7, 6])