# Indexing and Slicing

In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
array[0]

1

In [4]:
array[3]

4

In [5]:
array[0:4]

array([1, 2, 3, 4])

diziyi ters çevirme

In [6]:
array[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [7]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [11]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
matrix[1,1]

6

In [13]:
matrix[:,1]

array([2, 6])

In [14]:
matrix[1,1:4]

array([6, 7, 8])

In [15]:
matrix[-1,:]

array([5, 6, 7, 8])

In [16]:
matrix[:,-1]

array([4, 8])