# Numpy Basic Operators

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([9, 8, 7, 6])

In [3]:
array1 + array2

array([10, 10, 10, 10])

In [4]:
array1 - array2

array([-8, -6, -4, -2])

In [5]:
array1 ** array2

array([   1,  256, 2187, 4096], dtype=int32)

In [6]:
np.sin(array1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
array1 < 2

array([ True, False, False, False])

In [8]:
array1 * array2

array([ 9, 16, 21, 24])

In [9]:
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array4 = np.array([[9, 8, 7], [6, 5, 4]])

In [10]:
array3 * array4

array([[ 9, 16, 21],
       [24, 25, 24]])

In [11]:
np.exp(array3)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

matrix çarpımı: satır sütun sayıları eşit olması gerektiği için 2. matrisin transpozunu almak gerekebilir.

In [12]:
array3.dot(array4.T)

array([[ 46,  28],
       [118,  73]])

In [14]:
randomArray = np.random.random((5, 5))

In [15]:
randomArray

array([[0.88142054, 0.17488437, 0.06185633, 0.39602841, 0.51976181],
       [0.65121584, 0.16685078, 0.16277788, 0.88474922, 0.22725765],
       [0.68735575, 0.17227299, 0.83845815, 0.0102219 , 0.09815808],
       [0.77908179, 0.52498576, 0.25271809, 0.40038148, 0.09585508],
       [0.92108491, 0.21358147, 0.72344551, 0.31304344, 0.67055884]])

In [16]:
randomArray.sum()

10.828006085388806

In [17]:
randomArray.max()

0.9210849140340563

In [18]:
randomArray.min()

0.010221900728217048

matris satır değerlerini toplama

In [21]:
randomArray.sum(axis=0)

array([3.92015883, 1.25257537, 2.03925597, 2.00442446, 1.61159145])

matris sütun değerlerini toplama

In [22]:
randomArray.sum(axis=1)

array([2.03395146, 2.09285138, 1.80646687, 2.05302221, 2.84171417])

In [23]:
np.sqrt(randomArray)

array([[0.93884   , 0.41819178, 0.24870932, 0.62930788, 0.72094508],
       [0.80697946, 0.40847372, 0.40345741, 0.94061109, 0.47671548],
       [0.8290692 , 0.41505782, 0.91567361, 0.10110342, 0.31330189],
       [0.8826561 , 0.72455901, 0.50271075, 0.63275705, 0.30960472],
       [0.95973169, 0.46214876, 0.850556  , 0.55950285, 0.81887657]])

In [24]:
np.square(randomArray)

array([[7.76902170e-01, 3.05845418e-02, 3.82620495e-03, 1.56838504e-01,
        2.70152344e-01],
       [4.24082075e-01, 2.78391830e-02, 2.64966395e-02, 7.82781189e-01,
        5.16460383e-02],
       [4.72457922e-01, 2.96779831e-02, 7.03012074e-01, 1.04487254e-04,
        9.63500798e-03],
       [6.06968434e-01, 2.75610052e-01, 6.38664349e-02, 1.60305332e-01,
        9.18819655e-03],
       [8.48397419e-01, 4.56170453e-02, 5.23373408e-01, 9.79961925e-02,
        4.49649152e-01]])