# Numpy Basics

In [1]:
import numpy as np

np.array ile yeni bir dizi oluşturulabilir.

In [14]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

shape: dizinin boyutunu döndürür.

In [16]:
array.shape

(9,)

reshape: diziyi yeniden boyutlandırma

In [20]:
newArray = array.reshape(3,3)

In [21]:
newArray.shape

(3, 3)

Dimension: Dizi kaç boyutlu ?

In [22]:
newArray.ndim

2

dtype.name: dizi içerisindeki verilerin türlerini öğrenme

In [24]:
newArray.dtype.name

'int32'

size: Dizinin büyüklüğü

In [25]:
newArray.size

9

In [26]:
newArray2 = np.array([[1, 2, 3, 4], [9, 8, 7, 6]])

In [27]:
newArray2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

np.zeros: Elemanları sıfırlardan oluşan bir dizi oluşturur.

In [28]:
zerosArray = np.zeros((3,4))

In [29]:
zerosArray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Dizinin belirtilen elemanını değiştirme

In [30]:
zerosArray[0, 0] = 5

In [31]:
zerosArray

array([[5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

np.ones: Elemanları birlerden oluşan bir dizi oluşturur.

In [32]:
onesArray= np.ones((3, 4))

In [33]:
onesArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.empty: Boş dizi oluşturur.

In [37]:
emptyArray = np.empty((3,3))

In [38]:
emptyArray

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.13828272e-321],
       [0.00000000e+000, 0.00000000e+000, 9.02945628e-312]])

np.arange: Belirtilen sayıdan, belirtilen sayıya kadar belirtilen aralıklarla eleman ekleyerek dizi oluşturur.
ÖRNEĞİN: np.arange(10,50,5) 10'dan 50'ye kadar 5'er 5'er arttırarak dizi oluşturur.

In [41]:
arangeArray = np.arange(10,50,5)

In [42]:
arangeArray

array([10, 15, 20, 25, 30, 35, 40, 45])

np.linspace: Belirtilen aralıklarlarda belirtilen kadar sayı seçer.
ÖRNEĞİN: np.linspace(10,50,20)   # 10 ile 50 arasında 20 tane sayı seçer.

In [44]:
linspaceArray=np.linspace(10,50,20)

In [45]:
linspaceArray

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])