# Shape Manipulation

In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ravel: matrisleri vektör haline getirir. Çok kullanılan bir fonksiyondur.

In [7]:
array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arrayTranspose = array.T

In [10]:
arrayTranspose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
newArray = np.array([[1, 2], [3, 4], [5, 6]])

In [12]:
newArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
newArray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
newArray

array([[1, 2],
       [3, 4],
       [5, 6]])

reshape ile matrislerin boyutu değiştirildiğinde değişikliğin kalıcı olması için yeni bir değişkene atama yapmak gerekir.

resize ise değişikliği direk aynı matrise uyguladığı için yeni bir değişkene atama yapmasak bile kalıcı olur. yukarıda reshape örneği var. aşağıda resize örneği verilmiştir.

In [15]:
newArray.resize(2,3)

In [16]:
newArray

array([[1, 2, 3],
       [4, 5, 6]])

Görüldüğü gibi reshape yaptıktan sonra newArray çağrıldığında yine ilk hali olarak geldi. Fakat resize yaptıktan sonra newArray çağrıldığında yapılan yeniden boyutlandırma kalıcı oldu.